name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'lambda_function.py'

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.access_key }}
          aws-secret-access-key: ${{ secrets.secret_key }}

          aws-region: us-east-1

      - name: Deploy Lambda Function # Zips lambda directory and updates lambda function
        run: 
            zip -r lambda.zip .
            aws lambda update-function-code --function-name my-lambda-cicd --zip-file fileb://lambda.zip